# TEXT ENCODER CONFIG
text_model: 'bert-base-uncased'
text_len: 100
transformer_embed_dim: 768
freeze_text_encoder_weights: True

# AUDIO ENCODER CONFIG
audioenc_name: 'Cnn14'
out_emb: 2048
sampling_rate: 44100
duration: 5
fmin: 50
fmax: 14000
n_fft: 1028
hop_size: 320
mel_bins: 64
window_size: 1024

# PROJECTION SPACE CONFIG 
d_proj: 1024
temperature: 0.003
num_classes: 527

# TRAINING AND EVALUATION CONFIG
prompt: True
prompt_len: 32
lr: 0.002
model_fp: '../../CLAP_weights_2022.pth'
use_cuda: True
epochs: 10
batch_size: 24